runtime: python37
entrypoint: gunicorn -b :$PORT main:app
instance_class: F2
service: api

env_variables:
  CLOUD_SQL_CONNECTION_NAME: cis3111-2023-class:europe-west1:db-instance
  DB_USER: root
  DB_PASSWORD: DO\K4Rs<_-YPre8x
  DB_NAME: numbersdb

automatic_scaling:
  min_instances: 5
  max_instances: 15
